get_module_deps3.py: Check attribute '__file__'
Source: poky
MR: 123706
Type: Integration
Disposition: Merged from poky
ChangeID: f9679ac9f89d371c1934ccb319eb3c3eae33d61d
Description:

Check if the module object has attribute '__file__' to fix and
avoid errors like:

AttributeError: module '_abc' has no attribute '__file__'. Did you mean: '__name__'?

(From OE-Core rev: 1684457df9fb7029a276df4438c8fc4a17e3e1e9)

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
(cherry picked from commit 8acce12c1a4cf37ac312c92d62a6ae93a349dddf)
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>