python3: skip tests requiring tools-sdk
Source: poky
MR: 110389
Type: Integration
Disposition: Merged from poky
ChangeID: 857a540838b74b2a0ee868b9e801dc104c9a540a
Description:

Conditionally skip test_ctypes.test_find unless
IMAGE_FEATURES contains 'tools-sdk' as these test
cases require full packagegroup-core-buildessential

Fixes:
AssertionError: Failed ptests:
{'python3': ['test_find_library_with_gcc', 'test_find_library_with_ld']}

(From OE-Core rev: 63bc36dbd93c46be8adf7db00e3fc22897eb1846)

Signed-off-by: Tim Orling <timothy.t.orling@intel.com>
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>