rootfs-postcommads: Disable write_image_manifest by default
We now generate SPDX output by default and this is more powerful than any
simple manifest output. The current manifest is also in a hard to parse
format which is something we want to move away from.

Disable the image manifest writing by default going forward for the
above reasons.

(From OE-Core rev: a9e0be8abc7a91c4216864b8edaf96dfb0950b2c)

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

[
Can't do this due to:File: '/srv/pokybuild/yocto-worker/qemuarm-alt/build/meta/lib/oeqa/runtime/context.py', lineno: 192, function: readPackagesManifest
     0188:
     0189:    @staticmethod
     0190:    def readPackagesManifest(manifest):
     0191:        if not manifest or not os.path.exists(manifest):
 *** 0192:            raise OSError("Manifest file not exists: %s" % manifest)
     0193:
     0194:        image_packages = set()
     0195:        with open(manifest, 'r') as f:
     0196:            for line in f.readlines():
Exception: OSError: Manifest file not exists: /srv/pokybuild/yocto-worker/qemuarm-alt/build/build/tmp/deploy/images/qemuarm/core-image-full-cmdline-qemuarm.rootfs.manifest

ERROR: Logfile of failure stored in: /srv/pokybuild/yocto-worker/qemuarm-alt/build/build/tmp/work/qemuarm-poky-linux-gnueabi/core-image-sato-sdk/1.0/temp/log.do_testimage.347593
NOTE: recipe core-image-sato-sdk-1.0-r0: task do_testimage: Failed
ERROR: Logfile of failure stored in: /srv/pokybuild/yocto-worker/qemuarm-alt/build/build/tmp/work/qemuarm-poky-linux-gnueabi/core-image-sato/1.0/temp/log.do_testimage.347594
NOTE: recipe core-image-sato-1.0-r0: task do_testimage: Failed
ERROR: Logfile of failure stored in: /srv/pokybuild/yocto-worker/qemuarm-alt/build/build/tmp/work/qemuarm-poky-linux-gnueabi/core-image-full-cmdline/1.0/temp/log.do_testimage.347595
NOTE: recipe core-image-full-cmdline-1.0-r0: task do_testimage: Failed

e.g. https://autobuilder.yoctoproject.org/valkyrie/#/builders/74/builds/995
]

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>