dtc: Fix array-bounds error
Source: poky
MR: 108245
Type: Integration
Disposition: Merged from poky
ChangeID: 16128ae8dcdd1270a0e2336e6f805077a9406c09
Description:

Fixes
| libfdt/libfdt.h:251:28: error: array subscript 'struct fdt_header[0]' is partly outside array bounds of 'unsigned char[4]' [-Werror=array-bounds]
|   251 |                 fdth->name = cpu_to_fdt32(val); \
|       |                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~

(From OE-Core rev: 7f1968a096301aade2afc4b7eceb7a69e4ab364c)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit cd4fe4ec658ce4861fc970149f78b0ca7fda8fe0)
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>