mc: set ac_cv_path_ZIP to avoid buildpaths QA issues
Source: poky
MR: 175336
Type: Integration
Disposition: Merged from poky
ChangeID: 78626a6f1861361bbd78a411cb27b093e34b466b
Description:

* in builds with zip in HOSTTOOLS mc fails with:
  ERROR: mc-4.8.31-r0 do_package_qa: QA Issue: File /usr/libexec/mc/extfs.d/uzip in package mc-helpers-perl contains reference to TMPDIR [buildpaths]
  and it's because of the path to zip:
  mc/4.8.31/package $ grep -R styhead .
  ./usr/libexec/mc/extfs.d/uzip:my $app_zip = "TMPDIR/hosttools/zip";

* don't use /usr/bin/env as in other cases, because app_zip is then used e.g. with:
  my $cmd_addlink = "$app_zip -g -y";

(From OE-Core rev: 4003b5faa1e5acfa025e1d0df4e021e06cf8724c)

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>