systemd: backport another change from v252 to fix build with CVE-2022-45873.patch
Source: poky
MR: 124046, 123706
Type: Security Fix
Disposition: Merged from poky
ChangeID: 80dee2dad3e9dfdfb7ebb873d863c37a4f491834
Description:

* CVE-2022-45873.patch was backported from systemd/main, but it doesn't
  build without another change from v252 when elfutils PACKAGECONFIG is
  enabled.

* fixes:
  | ../git/src/shared/elf-util.c: In function 'parse_elf_object':
  | ../git/src/shared/elf-util.c:792:27: error: void value not ignored as it ought to be
  |   792 |                         r = json_variant_dump(package_metadata, JSON_FORMAT_FLUSH, json_out, NULL);
  |       |                           ^

(From OE-Core rev: bc8501a5a2ffc5673bad50f744d78822525bea9d)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>