package.py: Fix static debuginfo split
Source: poky
MR: 158408
Type: Integration
Disposition: Merged from poky
ChangeID: 648d2617ba5538ee22ad8ac7dd33684ea6256c03
Description:

Fix:
  NameError: name 'shutil' is not defined

(From OE-Core rev: a9d8e3f12032c92fa8dd7f2ad40f618da5ee281a)

Signed-off-by: Mark Hatle <mark.hatle@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@kernel.crashing.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 13bdd750ae54d57a5f459e4b7d8636c864978241)
Signed-off-by: Mark Hatle <mark.hatle@kernel.crashing.org>
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>