freetype: fix CGX2.4 undefined reference to `ADD_INT'
Source: MontaVista Software, LLC
MR: 126012
Type: Defect Fix
Disposition: Local
ChangeID: cb90b0c43f4d35491aae6f0961b4a4fa586cb441
Description:

fix CGX2.4 undefined reference to `ADD_INT' compilation error

Added missing ADD_INT macro in ftcalc.h header file.

Signed-off-by: Vivek Kumbhar <vkumbhar@mvista.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>