rt-tests: rt_bmark.py: fix TypeError
Source: poky
MR: 158408
Type: Integration
Disposition: Merged from poky
ChangeID: 4aa7d1ea8712f0136a8777d6d384be7d00a4c1a2
Description:

Fix following error:
  File "/usr/lib64/rt-tests/ptest/./rt_bmark.py", line 287, in run_cyclictest_once
    m = rex.search(line)
        ^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object

(From OE-Core rev: 9563027c35a4b1961a83100e22d4ea4430abd8b9)

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit c5108da4009ccd3dfc92632171d6bc4dae4507db)
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>