elfutils: don't add -Werror to avoid discarded-qualifiers
Source: poky
MR: 395209
Type: Integration
Disposition: Merged from poky
ChangeID: cc361cd49b872c8af2adb3ddf8387c4892ea0b61
Description:

With glibc-2.43 on host elfutils-native fails with:
elfutils-0.191/libcpu/riscv_disasm.c:1259:46: error: initialization discards âconstâ qualifier from pointer target type [-Werror=discarded-qualifiers]

elfutils-0.194 in master doesn't have this issue thanks to this patch avoiding -Werror from:
https://git.openembedded.org/openembedded-core/commit/?id=1d6ac3c811798732e6addc798656bbe104661d77

(From OE-Core rev: 7d9d9bcb64094da7121c6d6ce89cf07640537182)

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Yoann Congal <yoann.congal@smile.fr>
Signed-off-by: Paul Barker <paul@pbarker.dev>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>