libubootenv: backport patch to fix unknown type name 'size_t'
Source: poky
MR: 181536
Type: Integration
Disposition: Merged from poky
ChangeID: 6b05a9736953089e1f900a1c49cca37404737cfd
Description:

Fix:
../recipe-sysroot/usr/include/libuboot.h:29:2: error: unknown type name 'size_t'
size_t          envsize;
^

This error can be avoided by using CXXFLAGS:append = " -include cstddef"
but this way would be needed in all recipes that use libuboot.h.
Therefore, Backport the patch to include <cstddef> in C++ builds.

(From OE-Core rev: e401a16d8e26d25cec95fcea98d6530036cffca1)

Signed-off-by: Youngseok Jeong <youngseok1.jeong@lge.com>
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>