libgfortran.inc: fix nativesdk-libgfortran dependencies
Source: poky
MR: 158408
Type: Integration
Disposition: Merged from poky
ChangeID: c5e5c3534cb8bf80c997b1a1d7306df0a63793e5
Description:

* use virtual/* variables as INHIBIT_DEFAULT_DEPS does to avoid dependency on gcc-cross-
  from nativesdk-libgfortran

* the dependency was added in:
  https://git.openembedded.org/openembedded-core/commit/?id=00fba52c8a6f6383137cf89fc7aa34cc3e2ff45f
  causing:

  build/oe-core $ bitbake -g nativesdk-libgfortran
  NOTE: Resolving any missing task queue dependencies
  ERROR: Nothing PROVIDES 'gcc-cross-x86_64' (but virtual:nativesdk:/OE/build/oe-core/openembedded-core/meta/recipes-devtools/gcc/libgfortran_14.1.bb DEPENDS on or otherwise requires it). Close matches:
  gcc-cross-aarch64
  ...

  with:
  MACHINE=qemuarm64
  FORTRAN:forcevariable = ",fortran"

* after:
  https://git.openembedded.org/openembedded-core/commit/?id=44fc7aa1468ff042739cc5a91c84ef5c2a09e0a3
  nativesdk-libgfortran is pulled as dependency of nativesdk-gcc so this affects
  more people who didn't explicitly use nativesdk-libgfortran before

* the INHIBIT_DEFAULT_DEPS and gcc-runtime was there since gcc-4.8:
  https://git.openembedded.org/openembedded-core/commit/?id=a5e7ee5770b9e0cf719c573efffd874440f74289

(From OE-Core rev: 63ecb048f8238f67e21f77512b5276021b060d64)

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 5ce2e9c66cd2c08e141913ec65386f940353a8c5)
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>