libstd-rs: Switch to test rather then std for source
Source: poky
MR: 592186
Type: Defect Fix
Disposition: Backport from OE-Core commit 55dbedbd24
ChangeID: 72545cdbef5b183276fcd4c44089e59486a9413a
Description:

  issue: cargo failed to build with error[E0463]: can't find crate for `proc_macro`

  fix: Switch to test rather then std for source

Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>