oe-setup-build: Fix typo
Source: poky
MR: 395209
Type: Integration
Disposition: Merged from poky
ChangeID: 26475426bdb4f3c856b7a8b21367ca3b4a1d5aad
Description:

A variable was mistyped in an error message resulting in this error:

NameError: name 'tempalte_name' is not defined. Did you mean: 'template_name'?

(From OE-Core rev: 2b69c249ab3e2fc0ffb6196080fe35266ee91bd3)

Signed-off-by: Ryan Eatmon <reatmon@ti.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 275a3c015d37729c3b0c9cc4395d50ea2f210f02)
Signed-off-by: Clayton Casciato <majortomtosourcecontrol@gmail.com>
Signed-off-by: Yoann Congal <yoann.congal@smile.fr>
Signed-off-by: Paul Barker <paul@pbarker.dev>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>