rxvt-unicode: Do not use throw specifications
Source: poky
MR: 108245
Type: Integration
Disposition: Merged from poky
ChangeID: ad35a4bcb531696d32726f21703ec0c7cdaf5e76
Description:

Fixes build with -std=c++17

| ../../rxvt-unicode-9.22/src/../libev/ev++.h:379:46: error: ISO C++17 does not allow dynamic exception specifications
|   379 |     default_loop (unsigned int flags = AUTO) throw (bad_loop)
|       |                                              ^~~~~

(From OE-Core rev: 5cdb675b4219e33eb9f8a5b3be1a6c9efe2099fc)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit f437b226aac498240bc1e3a02eb0257a7deeedea)
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>