rt-tests: set branch name in SRC_URI
Source: poky
MR: 112421
Type: Integration
Disposition: Merged from poky
ChangeID: d1a90797828b7de6c8b2628db9edfbb4c05bf1b3
Description:

Upstream repo no longer has 'master' branch, and switched to
'main'. To avoid issue such as:

ERROR: rt-tests-1_1.1-r0 do_fetch: Fetcher failure: Unable to find
revision dff174f994f547a5785d32454865f140daacb0f5 in branch master
even from upstream

we need to set the default branch name to 'main' in the recipe.

(From OE-Core rev: ed52bea54f135b7b5367a24bb3861d9bc0c53117)

Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>