boost: add charconv lib
Source: poky master
MR: 187715
Type: Enhancement
Disposition: Backport from Poky master
ChangeID: 4dfed23581ab25f032356bbf32f08c87d01ec598
Description:

In boost 1.85 a charconv implementation in c++11 was added
[https://www.boost.org/doc/libs/master/libs/charconv/doc/html/charconv.html]

This is already used in real life and e.g. building the current wesnoth release fails with:
| /usr/src/debug/wesnoth/1.19.9/src/utils/charconv.hpp:57:(.text+0x238b): undefined reference to `boost::charconv::to_chars(char*, char*, double, boost::charconv::chars_format)'

Add charconv to BOOST_LIBS to provide the library

(From OE-Core rev: 42d14c130f2159c1d9ea314acc93142e6ccb2761)

Signed-off-by: Markus Volk <f_l_k@t-online.de>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>