linux-yocto/5.10: update to v5.10.194
Source: poky
MR: 127628
Type: Integration
Disposition: Merged from poky
ChangeID: ad12417f38f342acf76feeacaaee2dea1577ba97
Description:

Updating  to the latest korg -stable release that comprises
the following commits:

    006d5847646b Linux 5.10.194
    d93ba6e46e5f rcu-tasks: Add trc_inspect_reader() checks for exiting critical section
    3e22624f8fd3 rcu-tasks: Wait for trc_read_check_handler() IPIs
    9190c1f0aed1 rcu-tasks: Fix IPI failure handling in trc_wait_for_one_reader
    ad4f8c117b8b rcu: Prevent expedited GP from enabling tick on offline CPU
    268e92252277 Revert "MIPS: Alchemy: fix dbdma2"
    79ea9eb723b7 Revert "drm/amdgpu: install stub fence into potential unused fence pointers"
    be4ccafc077f mhi: pci_generic: Fix implicit conversion warning
    df3427204f1d ARM: module: Use module_init_layout_section() to spot init sections
    b59cfee8d8a2 arm64: module: Use module_init_layout_section() to spot init sections
    943ed7dc5ee4 arm64: module-plts: inline linux/moduleloader.h
    ecd62c85120d module: Expose module_init_layout_section()
    4566606fe3a4 Linux 5.10.193
    b3ac2c1d725b mm,hwpoison: fix printing of page flags
    7f92be110c0f ASoC: Intel: sof_sdw: include rt711.h for RT711 JD mode
    32f71ef62737 mm: memory-failure: fix unexpected return value in soft_offline_page()
    20c2db79f157 mm: memory-failure: kill soft_offline_free_page()
    406166a3acd7 mm: fix page reference leak in soft_offline_page()
    749630ce9147 mm,hwpoison: refactor get_any_page
    0df5eaab03ed dma-buf/sw_sync: Avoid recursive lock during fence signal
    7592a392b3e1 pinctrl: renesas: rza2: Add lock around pinctrl_generic{{add,remove}_group,{add,remove}_function}
    91cbf41a9d8b clk: Fix undefined reference to `clk_rate_exclusive_{get,put}'
    148a86651caf scsi: core: raid_class: Remove raid_component_add()
    5d02f4320a95 scsi: snic: Fix double free in snic_tgt_create()
    d643d3f322e8 ASoC: rt711: add two jack detection modes
    c7b26063fcae drm/i915: Fix premature release of request's reusable memory
    2d69f68ad409 cgroup/cpuset: Free DL BW in case can_attach() fails
    4603c2a104bc sched/deadline: Create DL BW alloc, free & check overflow interface
    c9546921a4b9 cgroup/cpuset: Iterate only if DEADLINE tasks are present
    5ac05ce56843 sched/cpuset: Keep track of SCHED_DEADLINE task in cpusets
    b950133d9a73 sched/cpuset: Bring back cpuset_mutex
    312713e3eae3 cgroup/cpuset: Rename functions dealing with DEADLINE accounting
    b2125926ba66 timers/nohz: Switch to ONESHOT_STOPPED in the low-res handler when the tick is stopped
    ae4f109b954d tick: Detect and fix jiffies update stall
    c7e91047d345 torture: Fix hang during kthread shutdown phase
    4bc6a4fca1f0 x86/fpu: Set X86_FEATURE_OSXSAVE feature after enabling OSXSAVE in CR4
    9e0c0b4ce541 drm/display/dp: Fix the DP DSC Receiver cap size
    8735d1c66c7c drm/vmwgfx: Fix shader stage validation
    ff0639b222e7 PCI: acpiphp: Use pci_assign_unassigned_bridge_resources() only for non-root bus
    da4e9eff0f1e media: vcodec: Fix potential array out-of-bounds in encoder queue_setup
    d2540b5f5aa1 of: dynamic: Refactor action prints to not use "%pOF" inside devtree_lock
    851f686ed0f5 radix tree: remove unused variable
    3b9a61570bc1 lib/clz_ctz.c: Fix __clzdi2() and __ctzdi2() for 32-bit kernels
    72e4a5a28ebf batman-adv: Hold rtnl lock during MTU update via netlink
    ee1d443eefb2 batman-adv: Fix batadv_v_ogm_aggr_send memory leak
    0c6da1d84921 batman-adv: Fix TT global entry leak when client roamed back
    6f5d10c0ac60 batman-adv: Do not get eth header before batadv_check_management_packet
    7c0959088366 batman-adv: Don't increase MTU when set by user
    480f2a129d8d batman-adv: Trigger events for auto adjusted MTU
    0dbedf9afee3 selinux: set next pointer before attaching to list
    a54c2048cd75 nfsd: Fix race to FREE_STATEID and cl_revoked
    7c262127d264 NFS: Fix a use after free in nfs_direct_join_group()
    f3c5697aae62 mm: add a call to flush_cache_vmap() in vmap_pfn()
    c9a0e31d9239 clk: Fix slab-out-of-bounds error in devm_clk_release()
    f979b92db1f5 NFSv4: Fix dropped lock for racing OPEN and delegation return
    0a809e01578b ibmveth: Use dcbf rather than dcbfl
    ffde5f9e8876 bonding: fix macvlan over alb bond support
    615ea2603dc8 net: remove bond_slave_has_mac_rcu()
    c8e1e17dee53 rtnetlink: Reject negative ifindexes in RTM_NEWLINK
    7b79dabd639c rtnetlink: return ENODEV when ifname does not exist and group is given
    d64cdb9cb629 netfilter: nf_tables: fix out of memory error handling
    5db1249c70b1 net/sched: fix a qdisc modification with ambiguous command request
    3847137cd167 igb: Avoid starting unnecessary workqueues
    fa7d7a7f007b ice: fix receive buffer size miscalculation
    70dfdbba3070 net: validate veth and vxcan peer ifindexes
    67c8d7ef54df net: bcmgenet: Fix return value check for fixed_phy_register()
    92b20b1569eb net: bgmac: Fix return value check for fixed_phy_register()
    0b39e3070a00 ipvlan: Fix a reference count leak warning in ipvlan_ns_exit()
    8162b73eef40 dccp: annotate data-races in dccp_poll()
    403cc3e6253d sock: annotate data-races around prot->memory_pressure
    005b6572d039 octeontx2-af: SDP: fix receive link config
    b8205dfed681 tracing: Fix memleak due to race between current_tracer and trace
    9c2ceffd4e36 tracing: Fix cpu buffers unavailable due to 'record_disabled' missed
    0498107394d4 rbd: prevent busy loop when requesting exclusive lock
    5f1697523367 rbd: retrieve and check lock owner twice before blocklisting
    2547026bb8c4 rbd: make get_lock_owner_info() return a single locker or NULL
    145248ebe0b2 libceph, rbd: ignore addr->type while comparing in some cases
    61c303cfb135 drm/amd/display: check TG is non-null before checking if enabled
    b964eb37c020 drm/amd/display: do not wait for mpc idle if tg is disabled
    7e11c58b2620 ALSA: pcm: Fix potential data race at PCM memory allocation helpers
    8c3a4c3b6485 dm integrity: reduce vmalloc space footprint on 32-bit architectures
    4fdfd3d2f09a dm integrity: increase RECALC_SECTORS to improve recalculate speed
    570f52137e9a fbdev: fix potential OOB read in fast_imageblit()
    31131cce2455 fbdev: Fix sys_imageblit() for arbitrary image widths
    209a84a14c0c fbdev: Improve performance of sys_imageblit()
    188edaaaad21 MIPS: cpu-features: Use boot_cpu_type for CPU type based features
    61913b303b31 MIPS: cpu-features: Enable octeon_cache by cpu_type
    bda55fb5ca61 fs: dlm: fix mismatch of plock results from userspace
    c3a1c4d996bf fs: dlm: use dlm_plock_info for do_unlock_close
    d503919895d8 fs: dlm: change plock interrupted message to debug again
    1652bcbf9e71 fs: dlm: add pid to debug log
    e850cd32df9f dlm: replace usage of found with dedicated list iterator variable
    7b44c1f383a1 dlm: improve plock logging if interrupted
    cd689b59129f PCI: acpiphp: Reassign resources on bridge if necessary
    e82757215295 xprtrdma: Remap Receive buffers after a reconnect
    8a64aadc29ba NFSv4: fix out path in __nfs4_get_acl_uncached
    c6aecc29d29e objtool/x86: Fix SRSO mess

(From OE-Core rev: 5bdf0da0372084ca312428f4e2585833fc732e9b)

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>