python3-magic: add missing DEPENDS
Source: poky
MR: 113389
Type: Integration
Disposition: Merged from poky
ChangeID: e3fd874a5b49229119c678982890f69f0442873f
Description:

Since file-native is ASSUME_PROVIDED magic.mgc is not being staged.  As
a result diffoscope-native is failing with:

magic.MagicException: b'could not find any valid magic files!

Fix this by adding dependency on file-replacement-native

(From OE-Core rev: dcd8294f826f6e061cdd01c6c3594789ed46732e)

Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>