ptest-runner: Backport patch to fix inappropriate ioctl error
Source: poky
MR: 107825
Type: Integration
Disposition: Merged from poky
ChangeID: 4d2be9145de7885499b4a246ccffdf4e8337a9b8
Description:

The srcrev bump is actually bring single commit [1] on top of 2.4.0 which fixes ptest
runs with messges like

ERROR: Unable to detach from controlling tty, Inappropriate ioctl for device

[1] https://git.yoctoproject.org/cgit/cgit.cgi/ptest-runner2/commit/?id=834670317bd3f6e427e1ac461c07ada6b8936dfd

(From OE-Core rev: a724eeeead28cbe7cfb8ffbcf40f6ac29e22ff61)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 791da075619139fa55751f8013c73d2fbf0cf64c)
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>