populate_sdk_ext: write_local_conf add shutil import
Source: poky
MR: 170679
Type: Integration
Disposition: Merged from poky
ChangeID: 339c54b2207e17762a76c3fef704ce66e4b5f596
Description:

Add shutil import to resolve error:

Exception: NameError: name 'shutil' is not defined, Did you forget to import 'shutil'

(From OE-Core rev: 759fb4bb4f5d5cf7f124f64b9314a34e41f58d23)

Signed-off-by: Mark Hatle <mark.hatle@kernel.crashing.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit b64263a43b4d82f1ebba13815bccb8a8cd3127f9)
Signed-off-by: Mark Hatle <mark.hatle@kernel.crashing.org>
Signed-off-by: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>