staging.bbclass: avoid copying files into recipe-sysroot if files already exist
Source: MontaVista Software, LLC
MR: 124120
Type: Defect Fix
Disposition: Local
ChangeID: 02618d1a908d63d09b2ff54a3c2ed7e91d1beaa5
Description:
When the kernel configs are changed in the local.conf, the linux-mvista gets
rebuilt; this in turn makes dependent recipes of linux-mvitsa such as
openvswitch, lttng-modules to rebuild. During this process the files
under recipe-sysroot, from previous build still exist. And trying to copy
the same files again at the same locations causes below error:

-- snip --
Exception: FileExistsError: [Errno 17] File exists: '.../tmp/sysroots-components/x86_atom_64/linux-mvista/sysroot-providers/linux-mvista' -> '.../tmp/work/i586-montavistamllib32-linux/lib32-openvswitch/2.8.0+4c412d44755ac7dab4e003f31494868af9f5fec0-r0.13/lib32-recipe-sysroot/sysroot-providers/linux-mvista'
-- snip --

The change check for existence of file before copying, to fix
the error.

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>