psmisc: Add dependency on gettext-native
It solves below issue:
-- snip --
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
ERROR: autoreconf execution failed.
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>